Update de.html l. 874-1000
herrhundt/remember pull request #18
Opened 2020-05-15 06:45 UTC by Picman2000

Line 920

2020-05-15 06:51 UTC, herrhundt approved these changes

2020-05-15 06:51 UTC, herrhundt commented on de.html
> +	Jedes tägliches Spiel dauert 20-30 Minuten. Anstatt eine Serie im TV zu schauen,
```suggestion
	Jedes tägliche Spiel dauert 20-30 Minuten. Anstatt eine Serie im TV zu schauen,
```

2020-05-15 06:51 UTC, herrhundt commented on de.html
> +	kannst du dich ein <i>Leben lang</i> an alles mögliche erinnern!
```suggestion
	kannst du dich ein <i>Leben lang</i> an alles Mögliche erinnern!
```
https://www.korrekturen.de/wortliste/alles_moegliche.shtml

2020-05-15 20:34 UTC, its-nico requested changes

2020-05-15 20:34 UTC, its-nico commented on de.html
> +	Jedes tägliche Spiel dauert 20-30 Minuten. Anstatt eine Serie im TV zu schauen,
```suggestion
	Jedes tägliche Spiel dauert 20-30 Minuten. Anstatt in der Zeit eine Serie im TV zu schauen,
```

2020-05-17 13:53 UTC, its-nico approved these changes

2020-05-19 21:16 UTC, merged