Update de.html 501 - 686
herrhundt/remember pull request #8
Opened 2020-05-14 11:08 UTC by TubaKarte

2020-05-14 13:59 UTC, herrhundt commented on de.html
> +  Deshalb: Du lernst etwas am effizientesten...
am Effizientesten

2020-05-14 14:01 UTC, herrhundt reviewed
am effizientesten muss noch korrigiert werden: am Effizientesten

2020-05-15 16:19 UTC, its-nico commented on de.html
> +  Deshalb: Du lernst etwas am effizientesten...
Es müsste großgeschrieben werden, wenn es substantiviert wird, allerdings ist es hier ja immer noch ein Adjektiv.

2020-05-19 18:52 UTC, Picman2000 requested changes
line 673" ,**wodurch** du langsamer vergisst" passt glaube ich besser
line 687 das gleiche nochmal

2020-05-19 21:15 UTC, herrhundt commented on de.html
> +  Deshalb: Du lernst etwas am effizientesten...
Danke, hier habe ich etwas dazugelernt ;-)

2020-05-19 21:15 UTC, merged